config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :kittens

  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end

  end

  def show 
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
    
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    @kitten.save

    flash[:notice] = "Kitten Created"

    redirect_to root_path
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    @kitten.update_attributes(kitten_params)
    @kitten.save

    flash[:notice] = "Kitten Updated"

    redirect_to kitten_path(@kitten)
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    flash[:notice] = "Kitten Deleted"

    redirect_to root_path
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |form| %>
  <%= form.label :name, "Name:"%>
  <%= form.text_field :name, :value => params[:name] %>
  <%= form.label :age, "Age:" %>
  <%= form.select :age, [0, 1, 2, 3, 4, 5], :selected => params[:age] %>
  <%= form.label :cuteness, "Cuteness:" %>
  <%= form.select :cuteness, [1, 2, 3, 4, 5], :selected => params[:cuteness] %>
  <%= form.label :softness, "Softness:" %>
  <%= form.select :softness, [1, 2, 3, 4, 5], :selected => params[:softness] %>
  <%= form.submit "Submit" %>
<% end %>

app/views/kittens/edit.html.erb
<%= render "form" %>

<%= link_to "Back", kitten_path %>
<%= link_to "Delete", kitten_path, :method => "delete" %>

app/views/kittens/index.html.erb
<%= flash[:notice] %>

<h2> All Kittens </h2>

<% @kittens = Kitten.all %>

<% @kittens.each do |kitten| %>
  <%= link_to "#{ kitten.name }", kitten_path(kitten) %> <br>
  Age: <%= kitten.age %>
  Softness: <%= kitten.softness %>
  Cuteness: <%= kitten.cuteness %> <br> <br>
<% end %> 

<br>

<%= link_to "New Kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h3> Create Your Kitten </h3>

<%= render "form" %> <br>

<%= link_to "Back", root_path %>

app/views/kittens/show.html.erb
<% @kitten = Kitten.find(params[:id]) %>

<% if flash[:notice] %>
  <%= flash[:notice]%> <br>
<% end %>

<strong> <%= @kitten.name %> </strong> <br>
Age: <%= @kitten.age %>
Softness: <%= @kitten.softness %>
Cuteness: <%= @kitten.cuteness %> <br>

<%= link_to "Edit", edit_kitten_path({:name => @kitten.name, :age => @kitten.age, :cuteness => @kitten.cuteness, :softness => @kitten.softness }) %>
<%= link_to "Delete", kitten_path, :method => "delete" %>
<%= link_to "Back", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>